# DC/OS System Requirements as of https://docs.mesosphere.com/1.11/installing/production/system-requirements/
- name: "Gather OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "vars/generic.yml"
  tags: vars

- name: "Populate service facts"
  service_facts: {}

- name: "Disabled firewalld (Only on some platforms)"
  systemd:
    name: firewalld
    state: stopped
    enabled: false
  when: "'firewalld.service' in ansible_facts.services"

- name: "Disabled DNSmasq (Only on some platforms)"
  systemd:
    name: dnsmasq
    state: stopped
    enabled: false
  when: "'dnsmasq.service' in ansible_facts.services"

- name: Check for time sync guard file
  stat:
    path: /run/time_sync_done
    get_md5: no
    get_checksum: no
  register: time_sync_done_file

- block:
  - name: Check time sync
    shell: |
      chronyc tracking | awk '/Leap status/ {print $4}' | grep -qv "Not synchronised"
    register: chronyc_time_sync
    changed_when: false
    when: "'chronyd.service' in ansible_facts.services"

  - name: "Sync time with chronyc"
    shell: "chronyc -a 'burst 4/4' && sleep 5 && chronyc -a makestep"
    when: "'chronyd.service' in ansible_facts.services and (chronyc_time_sync.rc == 1 or not time_sync_done_file.stat.exists) and dcos_timesync"
    register: time_sync_done
  rescue:
    - name: Output
      fail:
        msg: >
          ABORT! Could not timesync with chronyc'.
          Please make sure that the setup of chronyd is correct!

- block:
  - name: Check time sync
    shell: |
      ntpstat | grep -qv 'unsynchronised'
    register: ntp_time_sync
    changed_when: false
    when: "'ntpd.service' in ansible_facts.services"

  - name: Stop service ntpd
    service:
      name: ntpd
      state: stopped
    when: "'ntpd.service' in ansible_facts.services and (ntp_time_sync.rc == 1 or not time_sync_done_file.stat.exists) and dcos_timesync"

  - name: "Sync time with ntpd"
    shell: "ntpd -gq"
    when: "'ntpd.service' in ansible_facts.services and (ntp_time_sync.rc == 1 or not time_sync_done_file.stat.exists) and dcos_timesync"
    register: time_sync_done

  - name: Start service ntpd
    service:
      name: ntpd
      state: started
    when: "'ntpd.service' in ansible_facts.services and (ntp_time_sync.rc == 1 or not time_sync_done_file.stat.exists) and dcos_timesync"
  rescue:
    - name: Output
      fail:
        msg: >
          ABORT! Could not timesync with ntpd'.
          Please make sure that the setup of ntpd is correct!

- name: Time sync guard file
  shell: touch /run/time_sync_done
  when: not time_sync_done_file.stat.exists

- name: Check if docker is already installed
  yum:
    list:
      - docker
      - docker-ce
  # If not installed yum_list_docker.results[*].yumstate != installed
  register: yum_list_docker

- name: "Docker CE (stable) repository (Only non-EL systems)"
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_distribution == 'CentOS' and yum_list_docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- block:
  - name: "Finding RHEL extras repository name (Only EL systems)"
    shell: |
      cat /etc/yum.repos.d/redhat* | grep -E '^\[.*extras.*\]$' | grep -vE 'debug|source' | tr -d '[|]'
    register: rhel_exras_repo_name
    changed_when: false
    when: ansible_distribution == 'RedHat'

  - name: "Docker installed"
    yum:
      name: "{{ dcos_docker_pkg_name }}"
      update_cache: true
      enablerepo: "{{ rhel_exras_repo_name.stdout | default('') }}"
      state: present
    register: dcos_yum_docker_install
    until: dcos_yum_docker_install is success
    retries: 3
    delay: 60
  rescue:
    - name: Output
      fail:
        msg: >
          ABORT! Could not install '{{ dcos_docker_pkg_name }}'. Please make sure RHEL *extras* repository is availble!
      when: ansible_distribution == 'RedHat'
    - name: Output
      fail:
        msg: "ABORTING! Could not install '{{ dcos_docker_pkg_name }}'."
      when: ansible_distribution != 'RedHat' and yum_list_docker.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: "Docker running (Only on some platforms)"
  systemd:
    name: "{{ dcos_docker_service_name | default('docker') }}"
    state: started
    enabled: true
  when: "'podman' not in (dcos_docker_service_name | default('docker'))"

- name: "Install EPEL repositories for required packages"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  register: dcos_yum_epel_install
  until: dcos_yum_epel_install is success
  retries: 3
  delay: 60

- block:
  - name: "Install required system packages"
    yum:
      name: "{{ dcos_prereq_packages }}"
      state: present
    register: dcos_yum_system_packages_install
    until: dcos_yum_system_packages_install is success
    retries: 3
    delay: 60
  rescue:
    - name: Output
      fail:
        msg: >
          ABORT! Could not install '{{ dcos_prereq_packages }}'.
          Please make sure the systems repositories are enabled and reachable!

- name: "SELinux '{{ dcos['selinux_mode'] | default('permissive') }}'"
  selinux:
    policy: targeted
    state: "{{ dcos['selinux_mode'] | default('permissive') }}"

- name: "Ensure groups 'nogroup' and 'docker' exist"
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - nogroup
    - docker
